### PR TITLE
[ADDED] Added Curd operation

### PR DESCRIPTION
**Pull request by skyline-r34v**
[ADDED] Added curd operation to activityBlueprint inside model folder in activityBlueprint.js file

Issue number - #215

### CODE REVIEW

**Review by TejasNair9977 — APPROVED** [review]
LGTM

**Review by ayushlohmod — APPROVED** [review]
looks gud!

**Comment by TejasNair9977** [comment]
ok i was gonna merge it anyway but please dont do it without me knowing @skyline-r34v

**Comment by skyline-r34v** [comment]
Sorry , won't happen again 💀

**Pull request merged**
