### PR TITLE
[Epic] Implemented endpoint, testcases and API documentation for Module model

### LINKED ISSUE #261: Create Endpoint for Module
The following tasks need to complete for the endpoint

- [x] #38 
- [x] #103 
- [ ] [Feat] Create endpoint for Module
- [ ] [Feat] Write all testcases for Module
- [ ] [Feat] Write all APIDOCs for Module

### PR DESCRIPTION
**Pull request by sumitst05**
## Description

- Created `routes/module.js` to handle requests related to modules.
- Implemented `services/module.js` to manage the logic for modules.
- Created `controller/module.js` to handle incoming module-related requests.
- Added test cases for the `/module/list` endpoint.
- Documented the `/module/list` endpoint.

## Images showing the generated apidoc:

swappy-20230828_223455

swappy-20230828_223509

## Related Epics or Issues:

- Fixes #261 
- Addresses:
   -  #262 
   - #263 
   - #264 

## Checklist

- [x] Code follows project's style guidelines.
- [x] Changes are documented appropriately.

### CODE REVIEW

**Review by TejasNair9977 — APPROVED** [review]
LGTM

**Review by Aastha-S-Rai — APPROVED** [review]
Good work !!!!

**Review by ayushlohmod — APPROVED** [review]
looks good!

**Review by TejasNair9977 — APPROVED** [review]
LGTM

**Pull request merged**
