### PR TITLE
213 Create paper model

### LINKED ISSUE #213: [Feat]: [Create a model for paper]
## Description

Create a paper model

This model will be named paper.js

create a schema with key and value pairs with appropriate conditions.
Models should be added to the model folder.

## Proposed Solution
```
answerSheetID: longInt
exam: Exam
student: Student
checkedBy: Faculty
mark: int
```

### PR DESCRIPTION
**Pull request by ANKIT638-ux**
## Description
Created paper model and added a mongoose-long package for storing long int values .

## Fixes
Fixes #213 

## Checklist

- [x] Code follows project's style guidelines.
- [x] Changes are documented appropriately.

## Notes
Check the mongoose-long package.

####  (PS →  Make Sure Pull request title is meaningful.)

### CODE REVIEW

**Comment by TejasNair9977** [comment]
Hey @ANKIT638-ux , this looks good but can you use a string instead of using mongoose long for answerSheetId? Sorry for the change in plans. Please reset the files other than the model file.

**Review by TejasNair9977 — CHANGES_REQUESTED** [review]
Replace Long with String.

**Comment by ANKIT638-ux** [comment]
Should I remove mongoose-long from package.json as well or do you want me to keep it

**Comment by TejasNair9977** [comment]
Ahh, @ANKIT638-ux  I'm sorry for the late reply, but since mongoose-long isnt being used, please remove that package as well, let the model be the only change in your PR.

**Review by kskarthik5 — COMMENTED** [review]
LGTM

**Review by TejasNair9977 — APPROVED** [review]
LGTM

**Pull request merged**
