### PR TITLE
[ADDED] Added validation for module.

### LINKED ISSUE #426: [Feat]: [Add Validation for Module]
## Description

There needs to be validation for all IDs in here. The validation must be done in the controller. You need to provide the service with a proper filter so that it can check if the ID provided in `req.body` actually exists for each collection that it belongs to. For example,
In `req.body` for adding Module, it needs to check that the provided IDs actually exist in the database. As always, never trust that the user is providing valid data.

## Use Case

It will make sure that data given by the user to the database is valid. 

## Proposed Solution

Right before the function that creates the document, check if the IDs provided by the user is valid.

### PR DESCRIPTION
**Pull request by deepti-50**
## Description
used middleware validate service for validating ids in controller/module.js file

## Fixes
Fixes #426 

## Checklist

- [ x] Code follows project's style guidelines.
- [x ] Changes are documented appropriately.

####  (PS →  Make Sure Pull request title is meaningful.)

### CODE REVIEW

**Comment by sumitst05** [comment]
Please do not open a PR on main 🙏🏻

**Comment by TejasNair9977** [comment]
uhhh you didnt add any commits??

**Comment by deepti-50** [comment]
> uhhh you didnt add any commits??

I did

**Comment by TejasNair9977** [comment]
if you did, its not pushed, please have a look at the commit list here

**Comment by TejasNair9977** [comment]
your commit is not here

**Comment by TejasNair9977** [comment]
image
further proof just so its clear

**Comment by deepti-50** [comment]
> image further proof just so its clear

let me commit again...will this be okay?

**Comment by TejasNair9977** [comment]
sure, please go ahead

**Comment by TejasNair9977** [comment]
duplicate

**Pull request closed without merging**
